import Head from 'next/head';
import { ReactNode } from 'react';
import Footer from './Footer';
import Header from './Header';
import { SelectedPage } from './shared/types';

type Props = {
  children: ReactNode;
  title: string;
  selectedPage: SelectedPage;
  setSelectedPage: (value: SelectedPage) => void;
};

const Layout = ({ children, title, selectedPage, setSelectedPage }: Props) => {
  return (
    <>
      <Head>
        <title>{title ? title + '-Page' : 'Blog'}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="overflow-hidden">
        <Header selectedPage={selectedPage} setSelectedPage={setSelectedPage} />
        <main>{children}</main>
        <Footer />
      </div>
    </>
  );
};

export default Layout;
